# Generated by Django 2.2.2 on 2019-08-28 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_auto_20190822_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journal_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
